### ISSUE TITLE
Scene Adoption: TODO / Missing items

### ISSUE THREAD

**Issue by JamesVanBoxtel** [panel-attack/panel-attack#584]
These issues should be resolved before sceneRefactor can be merged into beta or a different official release stream.

Feature parity:
- [x] 2 player local with the same controllers tested
- [x] use CustomRun again
- [x] #1002 
- [x] #1052
- [x] #1053
- [x] Implement select screen for 1p vs self
- [x] Implement select screen for training
- [x] Implement select screen for challenge mode
- [x] Implement select screen for 2p vs local
- [x] Implement select screen for 2p vs online
- [x] #1014 
- [x] #1027
- [x] #1035
- [x] #1064
- [x] #1054
- [ ] #1066
- [x] #1065 -> #1129
- [x] #1055
- [x] #1058
- [ ] #1059
- [x] #1060
- [x] Properly suppress SFX during unit tests
- [x] #1056
- [x] #1070
- [x] #1073
- [x] #1074
- [x] #1075 
- [x] #1083
- [x] #1082
- [x] #1086 
- [x] #1096
- [x] #1099 -> #1111
- [x] #1102
- [x] #1105
- [x] #1132 
- [x] #1133 
- [x] #1134 
- [x] #1135 
- [x] #1136
- [x] #1137 
- [x] #1143 
- [ ] #1144 
- [x] #1145 
- [x] #1147 
- [x] #1152
- [x] #1177

Clean code:
- [x] All consts refer to the new structure
- [x] Old input method removed and uses moved to new input
- [x] Old table util code removed, all uses moved over
- [x] #1097

New core features:
- [x] #1003
- [x] #758 
- [x] #637 
- [x] Training mode replays
- [x] Challenge mode replays
- [x] #624 

Bonus and QoL:
- [x] #1063
- [x] Make Carousel Buttons wider OR implement swipe controls for it https://github.com/Endaris/panel-attack/pull/12
- [x] Add touch buttons for page turn in select screen
- [x] #578
- [x] #693
- [x] #1004
- [x] #1108 -> #1114

The following bug issues will go stale with sceneRefactor. This does not mean they are fixed but the relevant code was changed enough to need to reconfirm their occurence (meaning to say they should be closed and reopened as necessary):
- #777 
- #776 
- #866 
- #861 
- #874 
- #1033 
- #107 
- #655 
- #694 
- #696
- #509
- #697 
- #717

**Comment by Endaris** [comment]
We should pin this issue so we don't forget about it while finalizing sceneRefactor.
I don't seem to have the necessary permissions to do so.

Also, change your initial post to a checkbox list if you can, so we can track better @JamesVanBoxtel

**Comment by Endaris** [comment]
- [ ] Make theme switching performant

**Comment by Endaris** [comment]
Closing the tracking issue as the merge happened and remaining items can be created as regular items contributing to the sceneRefactor milestone.
